version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8081:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/htpasswd:/etc/nginx/htpasswd
  app:
    build: ./app
    environment:
      - FLAG=FLAG{xxxxx}

