apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: gcr.io/namatyage/twctf-universal-app
    context: ./app
  - image: gcr.io/namatyage/twctf-universal-nginx
    context: ./nginx
deploy:
  kubectl:
    manifests:
      - k8s/*
