apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: asia-northeast1-docker.pkg.dev/twctf-2020-chals/angular-universal/app
    context: ./app
  - image: asia-northeast1-docker.pkg.dev/twctf-2020-chals/angular-universal/nginx
    context: ./nginx
deploy:
  kubectl:
    manifests:
      - k8s/*
