apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: asia-northeast2-docker.pkg.dev/twctf-2020-chals/angular-universal-v2/apache:latest
        name: apache
        ports:
        - containerPort: 80