apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG{xxxxx}
        image: gcr.io/namatyage/twctf-universal-app
        name: app
        ports:
        - containerPort: 4000