apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: FLAG
          valueFrom:
            secretKeyRef:
              name: flags
              key: flag1
        - name: FLAG2
          valueFrom:
            secretKeyRef:
              name: flags
              key: flag2
        image: asia-northeast1-docker.pkg.dev/twctf-2020-chals/angular-universal/app:latest
        name: app
        ports:
        - containerPort: 80