apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
  - "160.16.205.124/32"

