apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "160.16.205.124/32"
